# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import job_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dbm.proto',
  package='',
  serialized_pb='\n\tdbm.proto\x1a\tjob.proto\"\x90\x01\n\nExperiment\x12.\n\x03opt\x18\x01 \x01(\x0e\x32\x17.Experiment.OptionsMode:\x08PROTOBUF\x12\x14\n\x0clearningRate\x18\x02 \x01(\x01\x12\x16\n\x06layers\x18\x03 \x03(\x0b\x32\x06.Layer\"$\n\x0bOptionsMode\x12\x0c\n\x08PROTOBUF\x10\x01\x12\x07\n\x03\x43LI\x10\x02\"2\n\x05Layer\x12\x10\n\x08numNodes\x18\x01 \x01(\x05\x12\x17\n\x08isHidden\x18\x02 \x01(\x08:\x05\x66\x61lse:\x1e\n\x03\x65xp\x12\x04.Job\x18\x64 \x01(\x0b\x32\x0b.Experiment')


EXP_FIELD_NUMBER = 100
exp = descriptor.FieldDescriptor(
  name='exp', full_name='exp', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_EXPERIMENT_OPTIONSMODE = descriptor.EnumDescriptor(
  name='OptionsMode',
  full_name='Experiment.OptionsMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PROTOBUF', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CLI', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=133,
  serialized_end=169,
)


_EXPERIMENT = descriptor.Descriptor(
  name='Experiment',
  full_name='Experiment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='opt', full_name='Experiment.opt', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='learningRate', full_name='Experiment.learningRate', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='layers', full_name='Experiment.layers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPERIMENT_OPTIONSMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=169,
)


_LAYER = descriptor.Descriptor(
  name='Layer',
  full_name='Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='numNodes', full_name='Layer.numNodes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isHidden', full_name='Layer.isHidden', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=221,
)

_EXPERIMENT.fields_by_name['opt'].enum_type = _EXPERIMENT_OPTIONSMODE
_EXPERIMENT.fields_by_name['layers'].message_type = _LAYER
_EXPERIMENT_OPTIONSMODE.containing_type = _EXPERIMENT;
DESCRIPTOR.message_types_by_name['Experiment'] = _EXPERIMENT
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER

class Experiment(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXPERIMENT
  
  # @@protoc_insertion_point(class_scope:Experiment)

class Layer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAYER
  
  # @@protoc_insertion_point(class_scope:Layer)

exp.message_type = _EXPERIMENT
job_pb2.Job.RegisterExtension(exp)
# @@protoc_insertion_point(module_scope)
